name: WhoopWorld
favicon: null
layout_spectrum: 0.37428379082120955
typography_spectrum: 0.440876534441486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.161941172555089
  lightness: 0.0016511899884790182
  saturation: 0.15813124226406217
  rhythmicContrast: 0.45205077482387424
purpose: []
